services:
  triton:
    build:
      context: ./triton
    platform: "linux/amd64"
    ports:
      - 8000:8000
      - 8001:8001 
      - 8002:8002
    shm_size: '500MB'  #shared memory size
    restart: on-failure
    environment:
    - MODEL_REPOSITORY
    - CLIP_HF_REPO
    - CLIP_MODEL_PATH
    - CLIP_MODEL_VERSION
    - GEMMA_MODEL_PATH
    - GEMMA_MODEL_VERSION
    - HF_TOKEN
    volumes:
    - triton:/models

  weavmanage:
    build:
      context: ./weavmanage
    environment:
    - MILVUS_URI
    - MILVUS_TOKEN
    - MILVUS_DB
    - MILVUS_COLLECTION

  weavloader:
    build:
      context: ./weavloader
    ports:
      - 8081:8080
      - 5555:5555
    restart: on-failure
    environment:
    - TRITON_HOST
    - TRITON_PORT
    - MILVUS_URI
    - MILVUS_TOKEN
    - MILVUS_DB
    - MILVUS_COLLECTION
    - SAGE_USER
    - SAGE_PASS
    - CELERY_BROKER_URL
    - CELERY_RESULT_BACKEND
    - UNALLOWED_NODES
    - LOG_LEVEL
    - MONITOR_DATA_STREAM_INTERVAL
    - MONITOR_DATA_STREAM_QUERY_DELAY_MINUTE
    - LLM_RUN_MODE
    - NRP_API_KEY
    - NRP_API_ENDPOINT
    - NRP_LLM_MODEL
    - INIT_DATASET
    - INIT_DATASET_REVISION
    - INIT_DATASET_BATCH_SIZE
    - HF_TOKEN
    depends_on:
      - weavmanage
      - triton

  gradio-ui:
    build:
      context: ./app
    ports:
      - 7860:7860
    restart: on-failure
    environment:
    - MILVUS_URI
    - MILVUS_TOKEN
    - MILVUS_DB
    - MILVUS_COLLECTION
    - TRITON_HOST
    - TRITON_PORT
    - CLUSTER_FLAG
    - UNALLOWED_NODES
    - SAGE_USER
    - SAGE_PASS

volumes:
  triton:
