apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sage

namePrefix: dev-
commonLabels:
  env: dev

resources:
- ../base
- service-monitors.yaml
- ingress.yaml

patches:
  - path: gpus.yaml
    target:
      kind: Deployment
      labelSelector: "app=triton"
  - path: taint.yaml
    target:
      kind: Deployment
      labelSelector: "app in (gradio-ui, weavloader)"
  - path: gradio-env.yaml
    target:
      kind: Deployment
      labelSelector: "app=gradio-ui"
  - path: weavloader-env.yaml
    target:
      kind: Deployment
      labelSelector: "app=weavloader"
  - path: weavmanage-env.yaml
    target:
      kind: Job
      labelSelector: "app=weavmanage"

images:
  - name:  gitlab-registry.nrp-nautilus.io/ndp/sage/nrp-image-search/triton
    newTag: pr-19
  - name:  gitlab-registry.nrp-nautilus.io/ndp/sage/nrp-image-search/gradio-ui
    newTag: pr-19
  - name:  gitlab-registry.nrp-nautilus.io/ndp/sage/nrp-image-search/weavmanage
    newTag: pr-19
  - name:  gitlab-registry.nrp-nautilus.io/ndp/sage/nrp-image-search/weavloader
    newTag: pr-19
