apiVersion: apps/v1
kind: Deployment
metadata:
  name: PLACEHOLDER
spec:
  template:
    spec:
      tolerations:
      - key: nautilus.io/reservation
        operator: Equal
        value: sage
        effect: NoSchedule