apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradio-ui
  labels:
    app: gradio-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gradio-ui
  template:
    metadata:
      labels:
        app: gradio-ui
    spec:
      containers:
        - name: gradio-ui
          image: gitlab-registry.nrp-nautilus.io/ndp/sage/nrp-image-search/gradio-ui:latest
          imagePullPolicy: Always #TODO: remove once done with dev
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: MILVUS_DB
              value: "image_search_svc"
            - name: MILVUS_COLLECTION
              value: "SageImageSearch"
            - name: CLUSTER_FLAG
              value: "True"
            - name: TRITON_HOST
              value: "$(TRITON_SERVICE)"
            - name: TRITON_PORT
              value: "8001"
          envFrom:
          - secretRef:
              name: sage-user-secret
          - secretRef:
              name: milvus-secret
          resources:
            limits:
              cpu: 1
              memory: 5Gi
            requests:
              cpu: 1
              memory: 5Gi
          ports:
          - name: http
            containerPort: 7860
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gradio-ui
  labels:
    app: gradio-ui
spec:
  ports:
    - name: http
      port: 7860
      targetPort: 7860
  selector:
    app: gradio-ui
